---
kind: pipeline
name: default

trigger:
  branch:
    - master

steps:
  - name: Build
    image: klakegg/hugo
    commands:
      - hugo --destination /drone/src/build

  - name: Upload
    image: robvankeilegom/ssh-rsync
    environment:
      SSH_KEY:
        from_secret: drone_ssh_key
    commands:
      - eval `ssh-agent -s`
      - echo "$SSH_KEY" | ssh-add -
      - mkdir -p ~/.ssh
      - rsync -av /drone/src/build/ liezele.be:~/websites/liezele.be/current --delete

