---
kind: pipeline
name: default

trigger:
  branch:
    - master

steps:
  - name: Build
    image: klakegg/hugo
    commands:
      - hugo --destination /drone/src/build

  - name: Upload
    image: robvankeilegom/ssh-rsync
    environment:
      SSH_KEY:
        from_secret: drone_ssh_key
      SSH_USER:
        from_secret: drone_ssh_user
      SSH_PORT:
        from_secret: drone_ssh_port
    commands:
      - eval `ssh-agent -s`
      - echo "$SSH_KEY" | ssh-add -
      - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
      - ssh-keyscan -p $SSH_PORT liezele.be >> ~/.ssh/known_hosts
      - mkdir -p ~/.ssh
      - rsync -av -e "ssh -p $SSH_PORT" /drone/src/build/ $SSH_USER@liezele.be:~/websites/liezele.be/current --delete

