################################# Default configuration ###################
baseURL = "https://liezele.be"
title = "Home"
theme = "airspace"
defaultContentLanguage = "nl"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "30"
# disable language
disableLanguages = []
[markup]
  [markup.goldmark]
      [markup.goldmark.renderer]
            unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
# [[params.plugins.css]]
# link = "plugins/magnific-popup/magnific-popup.css"
# [[params.plugins.css]]
# link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
# [[params.plugins.js]]
# link = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
# [[params.plugins.js]]
# link = "plugins/shuffle/shuffle.min.js"
# [[params.plugins.js]]
# link = "plugins/google-map/gmap.js"
# [[params.plugins.js]]
# link = "plugins/instafeed/instafeed.min.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Over Liezele"
weight = 1
hasChildren = true

[[menu.main]]
name = "Geschiedenis"
parent = "Over Liezele"
url = "over/geschiedenis"

[[menu.main]]
name = "De Liezelenaar"
parent = "Over Liezele"
URL = "over/de-liezelenaar"

[[menu.main]]
name = "Fort Van Liezele"
parent = "Over Liezele"
URL = "over/fort-van-liezele"

[[menu.main]]
name = "De Watermolen"
parent = "Over Liezele"
URL = "over/de-watermolen"

[[menu.main]]
name = "De Kerk"
parent = "Over Liezele"
URL = "over/de-kerk"

[[menu.main]]
name = "Kapelletjes"
parent = "Over Liezele"
URL = "over/kapelletjes"

[[menu.main]]
name = "Verenigingen"
weight = 2
hasChildren = true

[[menu.main]]
name = "Landelijke Gilde"
parent = "Verenigingen"
URL = "verenigingen/landelijke-gilde"

[[menu.main]]
name = "Ferm"
parent = "Verenigingen"
URL = "verenigingen/ferm"

[[menu.main]]
name = "Chiro"
parent = "Verenigingen"
URL = "verenigingen/chiro"

[[menu.main]]
name = "De Bacchanten"
parent = "Verenigingen"
URL = "verenigingen/de-bacchanten"

[[menu.main]]
name = "Linsella"
parent = "Verenigingen"
URL = "verenigingen/linsella"

[[menu.main]]
name = "Okra"
parent = "Verenigingen"
URL = "verenigingen/okra"

[[menu.main]]
name = "Liebad"
parent = "Verenigingen"
URL = "verenigingen/liebad"

[[menu.main]]
name = "Onderwijs"
weight = 3
URL = "onderwijs"

[[menu.main]]
name = "Polyvalente Zaal"
weight = 4
URL = "polyvalente-zaal"

[[menu.main]]
name = "Lichtpuntjes Tocht"
weight = 5
URL = "posts/algemeen/lichtpuntjes-tocht-update"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Liezele, de groene long van Klein Brabant, is gelegen in de Belgische provincie Antwerpen en een deelgemeente van Puurs. Onze bruisende gemeenten bied een enorme diversiteit van wandelpaden en heeft als een van de enige in Vlaanderen het best bewaarde Fort uit WO I."
author = "Rob Van Keilegom"
# Contact Information
email = "info@liezele.be"
# Umami Analytics
umami_analytics_id = "93f15218-dd3c-4437-800d-8a1358dd97c1" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = false
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


################################ English Language ########################
[Languages.nl]
languageName = "nl"
languageCode = "nl-be"
contentDir = "content"
weight = 1
home = "Home"
# copyright
copyright = "Iets fout of onvolledig? [info@liezele.be](mailto:info@liezele.be) - Made by [robvankeilegom.be](https://robvankeilegom.be)"

# Instagram feed
[params.instafeed]
enable = false
user_id = "4044026246"
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"
